[profile.default]
src = "src"
out = "artifacts"
optimizer = true
optimizer-runs = 20_000
auto_detect_libraries = true
solc = "0.8.26"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# OpenZeppelin
build_info = true
extra_output = ["storageLayout"]


[rpc_endpoints]
localhost = "${LOCALHOST_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
